services:

  mongodb:
    image: mongo
    container_name: mongo_db
    restart: always
    ports:
      - '27011:27017'
    networks:
      - app-tier1

  spring_boot_mongo:
    build:
      context: .
      dockerfile: ./Dockerfile  
    restart: always
    ports:
      - '8083:8080'
    depends_on:
      - mongodb
    networks:
      - app-tier1   

networks:
  app-tier1:
    driver: bridge